name: Trigger auto deployment for qr-asset-stickers

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/qr-asset-stickers-AutoDeployTrigger-0364a2df-9c91-4ead-b0c4-91683fecb0b7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.QRASSETSTICKERS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QRASSETSTICKERS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QRASSETSTICKERS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.QRASSETSTICKERS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QRASSETSTICKERS_REGISTRY_PASSWORD }}
          containerAppName: qr-asset-stickers
          resourceGroup: qrstickers-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


